const S={r:"home",private:false,cat:"All",price:"All",dist:"All"};
const restaurants=[
["O Marinheiro","Portuguese","€€",2.0,"Comida portuguesa e peixe."],
["Praia Grande","Seafood","€€€",1.2,"Peixe e marisco com ambiente junto ao mar."],
["Casa do Sushi","Sushi","€€€",1.5,"Sushi e cozinha japonesa."],
["La Dolce Vita","Italian","€€",1.0,"Cozinha italiana."],
["Algarve Fine Dining","Michelin","€€€€",5.8,"Opção para uma ocasião especial."]
];
const beaches=[["Praia da Oura Leste","150 m","A praia mais próxima do apartamento."],["Santa Eulália","800 m","Praia de areia e águas claras."],["Praia de Albufeira","1,2 km","Praia central com restaurantes e serviços."]];
const activities=[["🐬","Zoomarine","6 km · Família","Parque, apresentações e actividades aquáticas."],["⛵","Boat Tour","Marina de Albufeira","Grutas, costa e opções de sunset."],["🏄","Surf","Algarve","Aulas para iniciantes e intermédios."],["🍷","Wine Tasting","Algarve","Provar vinhos e produtos regionais."]];
function go(r){S.r=r;render();scrollTo(0,0)}
function row(i,t,p,r){return `<div class="row" ${r?`onclick="go('${r}')"`:""}><div class="ico">${i}</div><div class="grow"><h3>${t}</h3><p>${p}</p></div><b>›</b></div>`}
function card(i,t,p,r){return `<div class="card" ${r?`onclick="go('${r}')"`:""}><div class="ico">${i}</div><h3>${t}</h3><p>${p}</p></div>`}
function home(){return `<div class="hero"><span class="eyebrow">ALBUFEIRA · ALGARVE</span><h1>Tahys Oura<br>Apartment</h1><p>Your private guide to the Algarve.</p></div><section class="section"><h2>Welcome</h2><p class="sub">Um guia digital para tornar a estadia mais simples, confortável e memorável. O Tahys Oura fica na Quinta Pedra dos Bicos, em frente à Oura, com vista mar e cerca de 150 m da Praia da Oura Leste.</p><div class="grid">${card("🏠","The Apartment","Informação do apartamento, equipamentos e localização.","apartment")}${card("♧","My Stay","Tudo o que precisa antes e durante a estadia.","stay")}${card("🍽️","Eat & Drink","Restaurantes por cozinha, preço e distância.","restaurants")}${card("🏖️","Beaches","Praias próximas e recomendações.","beaches")}${card("🗺️","Discover","Locais a visitar no Algarve.","discover")}${card("🎯","Activities","Experiências para a sua estadia.","activities")}</div></section>`}
function apartment(){return `<section class="detail"><div class="photo">TAHYS OURA · QUINTA PEDRA DOS BICOS</div><h1>The Apartment</h1><p class="sub">Apartamento de 90 m², 2 quartos, 6 camas, 1 casa de banho e capacidade para 6 hóspedes. O anúncio indica vista mar, Wi‑Fi, cozinha, espaço de trabalho e acesso partilhado à praia.</p><div class="box"><h3>Location</h3><p>Praia da Oura Leste: ~150 m · Santa Eulália: ~800 m · Praia de Albufeira: ~1,2 km · Oura Strip: ~200 m · Intermarché: ~100 m · Aldi: ~400 m.</p></div><div class="box"><h3>Check-in / Check-out</h3><p>Check-in: 16:00–02:00 · Check-out: antes das 11:00.</p></div><button class="btn" onclick="go('stay')">Open My Stay</button></section>`}
function stay(){if(!S.private)return `<section class="login"><span class="eyebrow" style="background:var(--deep);color:#fff">PRIVATE GUEST AREA</span><h1>My Stay</h1><p class="sub">Introduza o código privado fornecido para a sua reserva.</p><input id="code" inputmode="numeric" placeholder="Guest code"><button class="btn" onclick="login()">Enter Guest Area</button><div class="notice">Código de demonstração V1.1: <b>1234</b>. Na versão de produção, cada reserva terá um código próprio.</div></section>`;return `<section class="section"><h2>My Stay</h2><p class="sub">Bem-vindo. Aqui encontra tudo o que precisa para a sua estadia.</p><div class="list">${row("🚕","Airport Transfer","Faro Airport → Tahys Oura","transfer")}${row("🎁","Welcome Amenities","Produtos e ofertas de boas-vindas","amenities")}${row("🛏️","Choose your pillows","Escolha o seu tipo de almofada","pillows")}${row("🛂","Guest Registration","Dados de hóspedes e documentação","registration")}${row("💶","Tourist Tax","Informação sobre taxa turística","tax")}${row("🔑","Keycard & Access","Entrada no edifício e apartamento","access")}${row("🛡️","Security","Segurança e emergência","security")}${row("📶","Wi‑Fi & Apartment Guide","Internet e equipamentos","wifi")}</div></section>`}
function priv(title,ico,body){return `<section class="detail"><div class="photo">${ico} ${title.toUpperCase()}</div><h1>${title}</h1>${body}<button class="btn alt" onclick="go('stay')">← Back to My Stay</button></section>`}
function restaurants(){let cats=["All","Seafood","Portuguese","Sushi","Italian","Michelin"];let a=restaurantsData();return `<section class="section"><h2>Eat & Drink</h2><p class="sub">Escolha por tipo de cozinha, preço e distância.</p><div class="tags">${cats.map(c=>`<button class="tag ${S.cat===c?"active":""}" onclick="S.cat='${c}';render()">${c}</button>`).join("")}</div><div class="filters"><select onchange="S.price=this.value;render()"><option>All</option><option>€</option><option>€€</option><option>€€€</option><option>€€€€</option></select><select onchange="S.dist=this.value;render()"><option value="All">Any distance</option><option value="1">≤ 1 km</option><option value="2">≤ 2 km</option><option value="5">≤ 5 km</option><option value="10">≤ 10 km</option></select></div><div class="list">${a.map(x=>row("🍽️",x[0],`${x[1]} · ${x[2]} · ${x[3]} km · ${x[4]}`)).join("")}</div></section>`}
function restaurantsData(){return restaurants.filter(x=>(S.cat==="All"||x[1]===S.cat)).filter(x=>S.price==="All"||x[2]===S.price).filter(x=>S.dist==="All"||x[3]<=+S.dist)}
function beaches(){return `<section class="section"><h2>Beaches</h2><p class="sub">As praias mais próximas do Tahys Oura.</p><div class="list">${beaches.map(x=>row("🏖️",x[0],x[1]+" · "+x[2])).join("")}</div></section>`}
function activities(){return `<section class="section"><h2>Activities</h2><p class="sub">Ideias para famílias, casais e aventura.</p><div class="grid">${activities.map(x=>card(x[0],x[1],x[2]+" · "+x[3])).join("")}</div></section>`}
function discover(){return `<section class="section"><h2>Discover Algarve</h2><p class="sub">Uma primeira selecção de locais e experiências. A V2 terá conteúdo administrável.</p><div class="list">${row("🏛️","Old Town Albufeira","Centro histórico, restaurantes e miradouros")}${row("🌊","Benagil Caves","Grutas e passeios de barco")}${row("🐓","Guia","Restaurantes famosos de frango à Guia")}${row("💦","Water Parks","Zoomarine, Slide & Splash e Aquashow")}</div></section>`}
function concierge(){return `<section class="section"><h2>Concierge</h2><p class="sub">Ajuda rápida durante a estadia.</p><div class="list">${row("💬","WhatsApp","Contactar o anfitrião")}${row("📞","Phone","Contactar o anfitrião")}${row("🚑","Emergency","112 · Portugal")}${row("📍","Location","Abrir localização em mapas")}</div></section>`}
function login(){if(document.getElementById("code").value==="1234"){S.private=true;go("stay")}else toast("Código incorrecto. Use 1234 na demonstração.")}
const routes={home,apartment,stay,restaurants,beaches,activities,discover,concierge,
transfer:()=>priv("Airport Transfer","🚕",`<div class="box"><h3>Transfer</h3><p>V2: formulário com voo, hora de chegada, passageiros, bagagem e pedido de transferência Faro → Tahys Oura.</p></div><button class="btn" onclick="toast('Pedido guardado no modo demonstração.')">Request Transfer</button>`),
amenities:()=>priv("Welcome Amenities","🎁",`<div class="box"><h3>Included</h3><p>Sabonete e gel de duche de qualidade superior. V2 permitirá personalizar pedidos e quantidades.</p></div>`),
pillows:()=>priv("Choose your pillows","🛏️",`<div class="box"><h3>Preference</h3><p><label><input type="radio" name="p" checked> Medium</label><br><label><input type="radio" name="p"> Soft</label><br><label><input type="radio" name="p"> Firm</label><br><label><input type="radio" name="p"> Memory Foam</label></p></div><button class="btn" onclick="toast('Preferência guardada.')">Save Choice</button>`),
registration:()=>priv("Guest Registration","🛂",`<div class="box"><h3>Secure registration</h3><p>A V2 deverá usar um formulário seguro para recolher os dados necessários à comunicação legal de hóspedes, com controlos RGPD e retenção adequada. Não inserir documentos reais nesta demonstração.</p></div><button class="btn" onclick="toast('Formulário seguro será ligado na V2.')">Start Registration</button>`),
tax:()=>priv("Tourist Tax","💶",`<div class="box"><h3>Informação do anúncio</h3><p>O anúncio informa €2/noite/hóspede, até 7 noites, com isenção para crianças e jovens até aos 13 anos. Confirmar sempre as regras municipais em vigor antes de usar esta informação operacionalmente.</p></div>`),
access:()=>priv("Keycard & Access","🔑",`<div class="box"><h3>Access</h3><p>V2: instruções exactas de entrada no edifício, keycard e apartamento, acompanhadas de fotografias.</p></div>`),
security:()=>priv("Security","🛡️",`<div class="box"><h3>Emergency</h3><p>Emergência em Portugal: 112. Os contactos privados de segurança podem ser adicionados no painel de administração.</p></div>`),
wifi:()=>priv("Wi‑Fi & Apartment Guide","📶",`<div class="box"><h3>Apartment guide</h3><p>V2: Wi‑Fi, Smart TV, ar condicionado, máquina de lavar, máquina de loiça e restantes equipamentos.</p></div>`)};
function render(){let f=routes[S.r]||home;document.getElementById("content").innerHTML=f();document.getElementById("title").textContent=S.r==="home"?"Guest Concierge":S.r==="stay"?"My Stay":S.r==="restaurants"?"Eat & Drink":S.r==="discover"?"Discover":S.r[0].toUpperCase()+S.r.slice(1);document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.r===S.r||(S.r==="restaurants"||S.r==="beaches"||S.r==="activities")&&b.dataset.r==="discover"))}
function toast(m){let t=document.getElementById("toast");t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",2400)}
document.getElementById("home").onclick=()=>go("home");document.getElementById("back").onclick=()=>go("home");document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>go(b.dataset.r));
window.addEventListener("load",()=>{if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});setTimeout(()=>{document.getElementById("splash").style.display="none"},450);render()});